alter session set "_ORACLE_SCRIPT" = TRUE;
--Creacion de Tablespaces
--tablespace de Users y roles
CREATE TABLESPACE TBS_USERS_DATA DATAFILE 'C:\Databases\Noticias\Usuarios_Data01.DBF' SIZE 97M DEFAULT STORAGE (INITIAL 5M NEXT 6M PCTINCREASE 0);
ALTER TABLESPACE TBS_USERS_DATA ADD DATAFILE 'C:\Databases\Noticias\Usuarios_Data02.DBF' SIZE 97M;
CREATE TABLESPACE TBS_USERS_IDX DATAFILE 'C:\Databases\Noticias\Usuarios_Idx01.DBF' SIZE 50M DEFAULT STORAGE (INITIAL 6M NEXT 10M PCTINCREASE 0);
--tablespace de noticias y reaccion de noticias
CREATE TABLESPACE TBS_NEWS_DATA DATAFILE 'C:\Databases\Noticias\Noticias_Data01.DBF' SIZE 90M DEFAULT STORAGE (INITIAL 5M NEXT 10M PCTINCREASE 0);
ALTER TABLESPACE TBS_NEWS_DATA ADD DATAFILE 'C:\Databases\Noticias\Noticias_Data02.DBF' SIZE 90M;
CREATE TABLESPACE TBS_NEWS_IDX DATAFILE 'C:\Databases\Noticias\Noticias_Idx01.DBF' SIZE 30M DEFAULT STORAGE (INITIAL 4M NEXT 7M PCTINCREASE 0);
ALTER TABLESPACE TBS_NEWS_IDX ADD DATAFILE 'C:\Databases\Noticias\Noticias_Idx02.DBF' SIZE 30M;
--CREACIONN DE TABLAS
CREATE TABLE ROLS (
   ROL_ID INTEGER NOT NULL CONSTRAINT PK_ROL_ID PRIMARY KEY USING INDEX TABLESPACE TBS_USERS_IDX,
   TIPO VARCHAR(20) NOT NULL
) TABLESPACE TBS_USERS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE USUARIOS (
   USER_ID INTEGER NOT NULL CONSTRAINT PK_USER_ID PRIMARY KEY USING INDEX TABLESPACE TBS_USERS_IDX,
   CORREO VARCHAR(60) NOT NULL CONSTRAINT UNQ_CORREO UNIQUE USING INDEX TABLESPACE TBS_USERS_IDX,
   NOMBRE VARCHAR(50) NOT NULL,
   APELLIDOS VARCHAR(50) NOT NULL,
   FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
   ESTADO NUMBER(1) NOT NULL,--1 activo, 0 suspendido
   CONTRASENA VARCHAR2(200) NOT NULL,
   ROL_ID INTEGER NOT NULL,
   CONSTRAINT FK_ROL_ID FOREIGN KEY (ROL_ID) REFERENCES ROLS(ROL_ID)
) TABLESPACE TBS_USERS_DATA STORAGE (INITIAL 6M NEXT 10M PCTINCREASE 0);

CREATE TABLE NOTICIAS (
   NOTICIA_ID INTEGER NOT NULL CONSTRAINT PK_NOTICIA_ID PRIMARY KEY USING INDEX TABLESPACE TBS_NEWS_IDX,
   LINK_IMAGEN VARCHAR2(100) NOT NULL,
   CATEGORIA VARCHAR2(50) NOT NULL,
   FECHA_CREACION_NOTICIA DATE DEFAULT SYSDATE NOT NULL,
   DESCRIPCION VARCHAR2(4000) NOT NULL,
   TITULO VARCHAR2(200) NOT NULL,
   USER_ID INTEGER NOT NULL,
   CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USUARIOS(USER_ID)
) TABLESPACE TBS_NEWS_DATA STORAGE (INITIAL 7M NEXT 10M PCTINCREASE 0);


CREATE TABLE REACCIONES (
   REACCION_ID INTEGER NOT NULL CONSTRAINT PK_REACCION_ID PRIMARY KEY USING INDEX TABLESPACE TBS_NEWS_IDX,
   TIPO_REACCION VARCHAR2(20) NOT NULL,--Like o comentario
   COMENTARIO VARCHAR(200) NULL,--Porque puede ser un like y ese tipo de reaccion no neceista este field.
   USER_ID INTEGER NOT NULL,
   NOTICIA_ID INTEGER NOT NULL,
   CONSTRAINT FK_USER_ID_R FOREIGN KEY (USER_ID) REFERENCES USUARIOS(USER_ID),
   CONSTRAINT FK_NOTICIA_ID_R FOREIGN KEY (NOTICIA_ID) REFERENCES NOTICIAS(NOTICIA_ID)
) TABLESPACE TBS_NEWS_DATA STORAGE (INITIAL 4M NEXT 6M PCTINCREASE 0);
