CREATE OR REPLACE FUNCTION FN_CANTIDAD_NOTICIAS( AUTOR_V IN VARCHAR2)
RETURN INTEGER 
AS 
AUTORD VARCHAR2(200);
TOTALD INTEGER;
BEGIN

        select AUTOR,COUNT(NOTICIA_ID) 
        INTO AUTORD,TOTALD
        FROM  VIEW_NOTICIAS
        WHERE AUTOR = AUTOR_V
        GROUP BY AUTOR, USER_ID;
        RETURN TOTALD;
END;
select Autor,FN_CANTIDAD_NOTICIAS(Autor)FROM  VIEW_NOTICIAS GROUP BY AUTOR, USER_ID;


--NOTICIAS MENOR A UN MES
CREATE OR REPLACE FUNCTION FN_NOTICIAS_1MES( NOTICIA_ID_V IN INTEGER)
RETURN INTEGER 
AS 
NOTICIA_ID_D INTEGER;
FECHA_D DATE;
TOTALD INTEGER;
BEGIN
        select  FECHA_CREACION_NOTICIA
        INTO FECHA_D
        FROM  NOTICIAS
        WHERE NOTICIA_ID=NOTICIA_ID_V;
        IF FECHA_D>= ADD_MONTHS(TRUNC(SYSDATE),-1) THEN
        TOTALD:=1;
        ELSE
        TOTALD:=0;
        END IF;
        RETURN TOTALD;
END;
select NOTICIA_ID,FN_NOTICIAS_1MES(NOTICIA_ID)FROM NOTICIAS ;


--1 week ago
CREATE OR REPLACE FUNCTION FN_NOTICIAS_1SEMANA( NOTICIA_ID_V IN INTEGER)
RETURN INTEGER 
AS 
NOTICIA_ID_D INTEGER;
FECHA_D DATE;
TOTALD INTEGER;
BEGIN
        select  FECHA_CREACION_NOTICIA
        INTO FECHA_D
        FROM  NOTICIAS
        WHERE NOTICIA_ID=NOTICIA_ID_V;
        IF FECHA_D>= TRUNC(SYSDATE)-7 THEN
        TOTALD:=1;
        ELSE
        TOTALD:=0;
        END IF;
        RETURN TOTALD;
END;
select NOTICIA_ID,FN_NOTICIAS_1SEMANA(NOTICIA_ID)FROM NOTICIAS ;

--1day ago

CREATE OR REPLACE FUNCTION FN_NOTICIAS_1DIA( NOTICIA_ID_V IN INTEGER)
RETURN INTEGER 
AS 
NOTICIA_ID_D INTEGER;
FECHA_D DATE;
TOTALD INTEGER;
BEGIN
        select  FECHA_CREACION_NOTICIA
        INTO FECHA_D
        FROM  NOTICIAS
        WHERE NOTICIA_ID=NOTICIA_ID_V;
        IF FECHA_D>= TRUNC(SYSDATE)-1 THEN
        TOTALD:=1;
        ELSE
        TOTALD:=0;
        END IF;
        RETURN TOTALD;
END;
select NOTICIA_ID,FN_NOTICIAS_1DIA(NOTICIA_ID)FROM NOTICIAS ;

---SELECT PARA CONSEGUIR ESTADISTICAS
SELECT COUNT(USER_ID) FROM USUARIOS;
SELECT COUNT(NOTICIA_ID) FROM NOTICIAS;
select NOMBRE_COMPLETO, TIPO_REACCION,COUNT(REACCION_ID) from  VIEW_REACCIONES
GROUP BY NOMBRE_COMPLETO,TIPO_REACCION;
select NOMBRE_COMPLETO,COUNT(REACCION_ID) from  VIEW_REACCIONES
GROUP BY NOMBRE_COMPLETO,USER_ID;
SELECT TITULO, COUNT(REACCION_ID), TIPO_REACCION from VIEW_REACCIONES
GROUP BY TITULO,TIPO_REACCION;