CREATE OR REPLACE VIEW VIEW_REACCIONES (REACCION_ID,NOMBRE_COMPLETO,TIPO_REACCION,COMENTARIO,TITULO,USER_ID,NOTICIA_ID, CONSTRAINT VIEW_REACCION_pk PRIMARY KEY (REACCION_ID)RELY DISABLE NOVALIDATE) AS
  SELECT R.Reaccion_ID, U.Nombre ||' '|| U.Apellidos as "Nombre_Completo", R.Tipo_reaccion, R.comentario,N.Titulo, U.USER_ID, N.NOTICIA_ID
  FROM Reacciones R
  INNER JOIN USUARIOS U
  ON U.USER_ID = R.USER_ID
  INNER JOIN Noticias N
  ON N.NOTICIA_ID= R.NOTICIA_ID
;
CREATE OR REPLACE VIEW VIEW_NOTICIAS (NOTICIA_ID,LINK_IMAGEN,CATEGORIA,ESCRIPCION,TITULO,FECHA_CREACION_NOTICIA, AUTOR, USER_ID, TIPO, CONSTRAINT VIEW_NOTICIA_pk PRIMARY KEY (NOTICIA_ID)RELY DISABLE NOVALIDATE) AS
  SELECT N.NOTICIA_ID,N.LINK_IMAGEN,N.CATEGORIA,N.DESCRIPCION, N.TITULO, N.FECHA_CREACION_NOTICIA, P.Nombre ||' '|| P.Apellidos as "AUTOR", P.USER_ID, R.TIPO FROM
  USUARIOS P
  Inner JOIN NOTICIAS N
  ON P.USER_ID=N.USER_ID
  INNER JOIN ROLS R
  ON P.ROL_ID=R.ROL_ID
;